### ISSUE TITLE
Halt on error

### ISSUE THREAD

**Issue by Ardusmith** [chillibasket/sd-config-file#2]
I used the SdConfigFile library successfully. However, if the SD slot has no card, I get a message that says "Do not reformat the SD card" (or similar), and then the sketch hangs.

Upon further inspection, I found this error handling function:  void errorHalt(print_t* pr)   in SdFat that prints that message, then executes a "while(true){}" statement, which (certainly?) is the source of the hang. I tried this using your example sketch as well, with the same result.

I realize this is not an issue of the SdConfigFile library, but I'm asking here if there is a workaround. Thank you for your work, and your time and reply.

**Comment by chillibasket** [comment]
I had a quick look and you are right, when the SD cannot initialise correctly the `errorHalt` function is called. This can be resolved in my library by removing lines [71](https://github.com/chillibasket/sd-config-file/blob/16258b7cbd4dbcdc06ba9b3b7c71746d818dc0bc/src/SdConfigFile.cpp#L71) and [109](https://github.com/chillibasket/sd-config-file/blob/16258b7cbd4dbcdc06ba9b3b7c71746d818dc0bc/src/SdConfigFile.cpp#L109) in `SDConfigFile.cpp`. The intention definitely was not for an error to cause the program to halt, so these calls are not correct for this situation.

**Comment by Ardusmith** [comment]
Thank you for that. It worked perfectly.

Side note: After making the changes to the library file, it is NOT automatically loaded at compile time, due to Arduino IDE caching of the original file. Select a different board (any board), compile the sketch, and then re-select your original board and compile/upload. This forces the compiler to load all library files again, which will now include the tweaked version.

**Comment by chillibasket** [comment]
This issue should now be resolved: 137dfdd2eafd0e7c8f698eaae88f037ac172ac7e
